export const Role = {
  ADMIN: 'ADMIN',
  FRANCHISE_STORE_STAFF: 'FRANCHISE_STORE_STAFF',
  MANAGER: 'MANAGER',
  SUPPLY_COORDINATOR: 'SUPPLY_COORDINATOR',
  CENTRAL_KITCHEN_STAFF: 'CENTRAL_KITCHEN_STAFF',
} as const;

export type Role = (typeof Role)[keyof typeof Role];
